### ISSUE TITLE
Bower errors

### ISSUE THREAD

**Issue by Diaoul** [BernardoSilva/angular-truncate#15]
When installing latest stable (0.1.5) bower complains about a few things:
- mismatch : Version declared in the json (0.1.4) is different than the resolved one (0.1.5)
- invalid-meta : angular-truncate-2 is missing "ignore" entry in bower.json

**Comment by BernardoSilva** [comment]
Thanks @Diaoul .
Fixed those warning and made those fix available as a new [release tag](https://github.com/BernardoSilva/angular-truncate/releases/tag/v0.2.0).
