### ISSUE TITLE
truncate middle - not to exceed 

### ISSUE THREAD

**Issue by nafnaf1000** [BernardoSilva/angular-truncate#20]
Is there a way to truncate the same way but in the middle of a string

not to exceed 
"the quick .....the lazy dog"

**Comment by BernardoSilva** [comment]
Hi @nafnaf1000 ,
I can't think you can do that at the moment, but is something that can be added if is really needed.
Can you describe a good use case, or your situations to prove if it worth add such a feature?

**Comment by nafnaf1000** [comment]
When dealing with a lot of information and limited on space...  Some times it is nicer to to show the begins and the end rather then just cut it off at some point. 

In my case my grid has alot of data.  Rather then cutting out things like title..  I can show part of it and and span the rest..  It looks better the  just cutting it off after word or letter count.

**Comment by zweeen** [comment]
I agree with @nafnaf1000 , for example showing a long path : the begins is important and also the end but not the middle of the path

**Comment by zweeen** [comment]
I found a solution, here a function that return a string truncated  in the middle: 

JS 

```
 $scope.truncate = function (fullStr, strLen) {
        if (fullStr.length <= strLen){
          return fullStr;
        }
        var separator = '...';
        var sepLen = separator.length,
            charsToShow = strLen - sepLen,
            frontChars = Math.ceil(charsToShow/2),
            backChars = Math.floor(charsToShow/2);

        return fullStr.substr(0, frontChars) + 
               separator + 
               fullStr.substr(fullStr.length - backChars);
    };
```

HTML

```
<div ng-repeat="file in files">
      {{truncate(file.name, 13)}}
</div>
```

If the "file.path" equals to = "MyNameIsBatman", then it will return the followinbg string : "MyNam...Batman".

Hope this help :)

**Comment by BernardoSilva** [comment]
thanks @zweeen .

Do you want to open a PR with that new feature?

I am a bit busy, might only have time to do that over the weekend.
But if you open the PR, I might accept it after review :)

**Comment by zweeen** [comment]
Hi @BernardoSilva ,

In your test File you are testing the **splitcharacters** filter :
[...]
`expect(characterFilter('123456789 10 11 12 13 14', 13)).toEqual('123456...2 13 14');`
[...]

so this filter can do the job to truncate the middle of a given string, I am right ? It seems that it does exactly what my function do.
If so, you should add it in the README :)

**Comment by BernardoSilva** [comment]
Hi @nafnaf1000 ,

You can see an example of how to trim the content in the middle by using the splitcharacter filter.

[See the demo page example](http://bernardosilva.github.io/angular-truncate-2/)

Thanks @zweeen for checking the code ;)

Added **characterfilter** zone on demo page for users to be able to play with it.

@nafnaf1000 does the **characterfilter** solves your problem?

**Comment by BernardoSilva** [comment]
Closing this since and example was added for this feature request.
